### ISSUE TITLE
微信聊天机器人实现——前期知识学习

### ISSUE THREAD

**Issue by kirito12138** [kirito12138/GroupWork#118]

**Comment by kirito12138** [comment]
学习了如何用wxpy库的功能，学习了如何用Python创建一个微信机器人与好友聊天功能，学习了如何用Python自动监听转发信息，测试了接受好友消息功能、接收群消息功能、转发有用群消息功能，目前版本具有监听特定群特定人消息功能。
https://mp.weixin.qq.com/s?__biz=MzA5MzY4NTQwMA==&mid=2651010904&idx=5&sn=3394233645a09db6e3a2476bcc808c0e&chksm=8bad84afbcda0db948d675afdb6230171a7cdfc9030c5d62696ed571874fc77b0975fbdf1b86&mpshare=1&scene=23&srcid=#rd
https://mp.weixin.qq.com/s?__biz=MzI0OTc0MzAwNA==&mid=2247484716&idx=1&sn=49b1b3c5cf0c14be0f3a2dab3ff2eed3&chksm=e98d96dfdefa1fc9d600b94fcc588cdefc60752058e1f85aa1c1f488d7558b9af1d688d3a1ee&scene=21#wechat_redirect

**Comment by awfsgdf** [comment]
学习了如何使用wxpy库的更多功能，学习了如何用Python创建一个微信机器人监控特定群聊的特定信息，其中具体实现了信息识别功能，进行了同时监控多个群聊的测试。
https://wxpy.readthedocs.io/zh/latest/
https://cloud.tencent.com/developer/article/1056208
